package com.cw.andoridmvp.db.greendaogen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cw.andoridmvp.bean.MarketMainModel;

import com.cw.andoridmvp.db.greendaogen.MarketMainModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig marketMainModelDaoConfig;

    private final MarketMainModelDao marketMainModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        marketMainModelDaoConfig = daoConfigMap.get(MarketMainModelDao.class).clone();
        marketMainModelDaoConfig.initIdentityScope(type);

        marketMainModelDao = new MarketMainModelDao(marketMainModelDaoConfig, this);

        registerDao(MarketMainModel.class, marketMainModelDao);
    }
    
    public void clear() {
        marketMainModelDaoConfig.clearIdentityScope();
    }

    public MarketMainModelDao getMarketMainModelDao() {
        return marketMainModelDao;
    }

}
